### ISSUE TITLE
Renaming rust-crypto crate to crypto

### ISSUE THREAD

**Issue by icorderi** [DaGenix/rust-crypto#153]
Hey, I wanted to suggest a rename of the `rust-crypto` crate to just `crypto`.

It can be done in the [Cargo.toml](https://github.com/DaGenix/rust-crypto/blob/master/Cargo.toml) leaving the package name intact by just renaming the crate.

``` toml
[lib]
# name = "rust-crypto"
name = "crypto"
path = "src/rust-crypto/lib.rs"
```

All import calls would then be:

``` rust
// extern crate "rust-crypto" as crypto; // old way
extern crate crypto; // new way
```

What do you think?
